name: base
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - papermill
  - jupytext
  - nbdime
  - libgcc
  - r-git2r
  - r-r.oo
  - r-dorng
  - r-statmod
  - r-foreach
  - r-foreach
  - r-r.utils
  - r::r-stringi
  - r-devtools
  - r-irkernel
  - r-pheatmap
  - r-snakecase
  - r-doparallel
  - r-data.table
  - r-tibble
  - r-rlang
  - r-downloader
  - r-dbi
  - r-readr
  - r-r.methodss3
  - r-gprofiler2
  - bioconductor-edger
  - bioconductor-limma
  - bioconductor-biobase
  - bioconductor-multtest
  - bioconductor-biomart
  - r-statmod
